version: '3.8'

services:
  guacd:
    image: guacamole/guacd
    container_name: guac-request-portal-guacd
    restart: unless-stopped
    networks:
      - default
    ports:
      - "4822:4822"

  postgres:
    image: postgres:15-alpine
    container_name: guac-request-portal-postgres
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  guacamole:
    image: guacamole/guacamole
    container_name: guac-request-portal-guacamole
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /opt/guacamole
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: changeme
      # Optional: Enable debug logging for development
      # LOG_LEVEL: "debug"
    volumes:
      - ./extensions:/opt/guacamole/extensions
    depends_on:
      - guacd
      - postgres

volumes:
  postgres-data:

networks:
  default:
    driver: bridge
