package com.guac.request.portal.rest;

import com.guac.request.portal.dao.RequestDAO;
import com.guac.request.portal.dao.RequestDAOMySQL;
import com.guac.request.portal.dao.RequestDAOPostgreSQL;
import com.guac.request.portal.model.AccessRequest;
import com.guac.request.portal.model.TargetEnvironment;
import com.guac.request.portal.util.GuacamoleProperties;
import org.apache.guacamole.GuacamoleException;
import org.apache.guacamole.net.auth.Credentials;
import org.apache.guacamole.net.auth.UserContext;


import org.apache.guacamole.rest.directory.DirectoryView.Field;
import org.apache.guacamole.rest.directory.DirectoryView.Type;
import org.apache.guacamole.rest.directory.DirectoryView.Visibility;
import org.apache.guacamole.rest.directory.DirectoryView.Permission;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRule;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleType;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleScope;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleLevel;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValue;
import org.apache.guacamole.rest.directory.DirectoryView.PermissionRule.RuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueRuleValueType;
import org.guac.request.portal.rest.AccessRequestResource;
import org.guac.request.portal.rest.TargetEnvironmentResource;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.Properties;

@Path("/request-portal")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class RequestPortalRESTResource {

    private final RequestDAO requestDAO;

    @Context
    private UserContext userContext;

    public RequestPortalRESTResource() throws GuacamoleException {
        Properties properties = GuacamoleProperties.getGuacamoleProperties();
        String databaseType = properties.getProperty("database-type"); // e.g., "mysql" or "postgresql"

        if ("mysql".equalsIgnoreCase(databaseType)) {
            this.requestDAO = new RequestDAOMySQL();
        } else if ("postgresql".equalsIgnoreCase(databaseType)) {
            this.requestDAO = new RequestDAOPostgreSQL();
        } else {
            throw new GuacamoleException("Unsupported database type specified in guacamole.properties: " + databaseType);
        }
    }

    @Path("/requests")
    public AccessRequestResource getAccessRequestResource() {
        return new AccessRequestResource(requestDAO, userContext);
    }

    @Path("/environments")
    public TargetEnvironmentResource getTargetEnvironmentResource() {
        return new TargetEnvironmentResource(requestDAO);
    }
}
